	<%@ page language="java" contentType="text/html; charset=utf-8"
    pageEncoding="utf-8"%>
	
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
	<meta property="qc:admins" content="10111430660216452061004162163757" />
	
    <title>iprinter</title>

    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="css/modern-business.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    
    <style type="text/css">
    body{padding-top: 0px;}
    .header-top {height:50px;}
    .navbar {border-radius: 0px; height: 80px;}
    .navbar-container, .navbar-header, .navbar-nav, .navbar-nav > li, .navbar-nav > li > a {height: 80px;}
	.navbar-nav > li > a {line-height: 50px; font-size: 18px; width: 102px; text-align: center;}
	.navbar-brand { height: 80px; line-height:80px; padding:0; margin-right:50px;}
	
	
	.navbar-inverse .navbar-nav>.active>a, .navbar-inverse .navbar-nav>.active>a:focus, .navbar-inverse .navbar-nav>.active>a:hover {
		border-bottom: 3px solid orange;
	}
	
    </style>

	<!-- qq互联js sdk -->
    <script type="text/javascript" src="http://qzonestyle.gtimg.cn/qzone/openapi/qc_loader.js" data-appid="101308502" data-redirecturi="http://1.iprinter0.applinzi.com/index.jsp" charset="utf-8" data-callback="true"></script>
		